version: '3.7'

services:
  database:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=easy_car
    image: postgres:latest
    volumes:
      - database_storage:/var/lib/postgresql/data
    networks:
      - backend

  app:
    container_name: app
    image: uladzislauc/easycar:v1final
    volumes:
      - images_store:/app/images
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  images_store:
  database_storage: